### ISSUE TITLE
restore issue

### ISSUE THREAD

**Issue by NareshDealer** [SungardAS/enhanced-snapshots#80]
Hi,
I tried to do some backup and restore where backup performed well but restore had the following issue.

2016-09-01 20:17:53.856 [ERROR] [pool-2-thread-1] AWSRestoreVolumeTaskExecutor - Failed to restore backup.
com.amazonaws.AmazonClientException: Unable to unmarshall response (ParseError at [row,col]:[100654,4]
Message: Read timed out). Response Code: 200, Response Text: OK
        at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:1295) ~[aws-java-sdk-core-1.10.60.jar:?]
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:870) ~[aws-java-sdk-core-1.10.60.jar:?]
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607) ~[aws-java-sdk-core-1.10.60.jar:?]
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376) ~[aws-java-sdk-core-1.10.60.jar:?]
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338) ~[aws-java-sdk-core-1.10.60.jar:?]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287) ~[aws-java-sdk-core-1.10.60.jar:?]
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:11132) ~[aws-java-sdk-ec2-1.10.60.jar:?]
        at com.amazonaws.services.ec2.AmazonEC2Client.describeSnapshots(AmazonEC2Client.java:6536) ~[aws-java-sdk-ec2-1.10.60.jar:?]
        at com.amazonaws.services.ec2.AmazonEC2Client.describeSnapshots(AmazonEC2Client.java:6548) ~[aws-java-sdk-ec2-1.10.60.jar:?]
        at sun.reflect.GeneratedMethodAccessor148.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[spring-aop-4.1.1.RELEASE.jar:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at com.sungardas.enhancedsnapshots.components.RetryInterceptor.invoke(RetryInterceptor.java:34) ~[RetryInterceptor.class:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at com.sun.proxy.$Proxy63.describeSnapshots(Unknown Source) ~[?:?]
        at com.sungardas.enhancedsnapshots.service.impl.AWSCommunicationServiceImpl.getSnapshot(AWSCommunicationServiceImpl.java:336) ~[AWSCommunicationServiceImpl.class:?]
        at com.sungardas.enhancedsnapshots.service.impl.AWSCommunicationServiceImpl.syncSnapshot(AWSCommunicationServiceImpl.java:194) ~[AWSCommunicationServiceImpl.class:?]
        at com.sungardas.enhancedsnapshots.service.impl.AWSCommunicationServiceImpl.waitForCompleteState(AWSCommunicationServiceImpl.java:183) ~[AWSCommunicationServiceImpl.class:?]
        at com.sungardas.enhancedsnapshots.tasks.executors.AWSRestoreVolumeTaskExecutor.restoreFromBackupFile(AWSRestoreVolumeTaskExecutor.java:179) [AWSRestoreVolumeTaskExecutor.class:?]
        at com.sungardas.enhancedsnapshots.tasks.executors.AWSRestoreVolumeTaskExecutor.execute(AWSRestoreVolumeTaskExecutor.java:74) [AWSRestoreVolumeTaskExecutor.class:?]
        at com.sungardas.enhancedsnapshots.components.WorkersDispatcher$TaskWorker.run(WorkersDispatcher.java:126) [WorkersDispatcher$TaskWorker.class:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[100654,4]
Message: Read timed out
        at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:591) ~[?:1.8.0_101]
        at com.sun.xml.internal.stream.XMLEventReaderImpl.peek(XMLEventReaderImpl.java:276) ~[?:1.8.0_101]
        at com.amazonaws.transform.StaxUnmarshallerContext.nextEvent(StaxUnmarshallerContext.java:207) ~[aws-java-sdk-core-1.10.60.jar:?]
        at com.amazonaws.services.ec2.model.transform.SnapshotStaxUnmarshaller.unmarshall(SnapshotStaxUnmarshaller.java:46) ~[aws-java-sdk-ec2-1.10.60.jar:?]
        at com.amazonaws.services.ec2.model.transform.DescribeSnapshotsResultStaxUnmarshaller.unmarshall(DescribeSnapshotsResultStaxUnmarshaller.java:53) ~[aws-java-sdk-ec2-1.10.60.jar:?]
        at com.amazonaws.services.ec2.model.transform.DescribeSnapshotsResultStaxUnmarshaller.unmarshall(DescribeSnapshotsResultStaxUnmarshaller.java:33) ~[aws-java-sdk-ec2-1.10.60.jar:?]
        at com.amazonaws.http.StaxResponseHandler.handle(StaxResponseHandler.java:99) ~[aws-java-sdk-core-1.10.60.jar:?]
        at com.amazonaws.http.StaxResponseHandler.handle(StaxResponseHandler.java:42) ~[aws-java-sdk-core-1.10.60.jar:?]
        at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:1250) ~[aws-java-sdk-core-1.10.60.jar:?]
        ... 27 more
2016-09-01 20:17:54.120 [INFO ] [pool-2-thread-1] AWSCommunicationServiceImpl - Volume vol-8fa2445a deleted
2016-09-01 20:17:54.120 [ERROR] [pool-2-thread-1] AWSRestoreVolumeTaskExecutor - Failed to execute restore task 7295daa1-f16a-4d30-a292-7d52417cad35. Changing task status to 'error'
2016-09-01 20:17:54.120 [ERROR] [pool-2-thread-1] AWSRestoreVolumeTaskExecutor - com.amazonaws.AmazonClientException: Unable to unmarshall response (ParseError at [row,col]:[100654,4]
Message: Read timed out). Response Code: 200, Response Text: OK

**Comment by NareshDealer** [comment]
can any one help on this.?

**Comment by KostiantynGlukhenko** [comment]
Hi Naresh,

Sorry for the delay. Can you please provide some extra information about your instance setup?
Like AWS region, enhanced snapshot version and etc. Any information can be very helpful.

Regards,
Kostiantyn

**Comment by NareshDealer** [comment]
@KostiantynGlukhenko  Thank you for reply.

Instance type
c4.xlarge

Availability zone
us-east-1c

Currently the volume is in Availability zone
us-east-1c

But i have selected to Availability zone
us-east-1b during the restore process, if that helps.

**Comment by rabay108** [comment]
@NareshDealer Also besides the information requested by Kostiantyn, whether the original EBS volume was created vanilla or from a snapshot or as part of a snapshot volume from a marketplace AMI. Volume size and used space will also be helpful.

**Comment by NareshDealer** [comment]
@rabay108 i have used the cloudformation stack in marketplace for setup, if this is what you are asking.

Thanks.

**Comment by rabay108** [comment]
@NareshDealer That's what I am getting to and see you can try backup-restore from a vanilla created volume vs the one created from a marketplace launch(Good to get the volume information on snapshots etc..), as I have heard in the past some issues with the volumes created from the marketplace software volumes.. Anyway @KostiantynGlukhenko will be looking in to the issue.

**Comment by NareshDealer** [comment]
@rabay108 thanks for the reply.. but can you guide me in how to use vanilla created volume. or any pre detailed instructions, if you can point me to.

Thanks.

**Comment by KostiantynGlukhenko** [comment]
@NareshDealer, can you please provide link to cloud formation template with you used for instance with issue? Since instance type c4.xlarge is not present in official cloud formation templates, did you modify it manually?

**Comment by NareshDealer** [comment]
@KostiantynGlukhenko The link on marketplace has been updated. 

This is the link i used for this.
https://aws.amazon.com/marketplace/pp/B01CIWY4UO

**Comment by rabay108** [comment]
@NareshDealer The mktplace link above there are 2 options
(1) Cloud creation stack - This is self contained and automatically will create the equivalent of the es-admin user
(2) Manually selecting the AMI, this scenario needs the IAM es-admin role equivalent to be selected.. which one of these you used? If it is #2 then the CFT comes to play as to which one was used?

**Comment by NareshDealer** [comment]
@rabay108  Sorry but i dont see second option, the only option was cloudformation stack. I didnt had another option when i built this server.
![image](https://cloud.githubusercontent.com/assets/20689530/18279746/39ca007e-741c-11e6-8615-a27fae42d082.png)

**Comment by rabay108** [comment]
When you click continue under deployment there are 2 options either to use cloud formation stack or using the AMIs in the list

**Comment by NareshDealer** [comment]
@rabay108 ![image](https://cloud.githubusercontent.com/assets/20689530/18280325/4dffec82-741e-11e6-949c-3ba79922a8d0.png)

**Comment by rabay108** [comment]
Other option with AMI existed in the links - https://github.com/SungardAS/enhanced-snapshots 
Can we assume you already built using the marketplace link v2.0 accepting the conditions and used the launch with cloud formation reporting the issue? Had this approach been used admin role wuld not have been the issue as it would have created and used the role automatically

**Comment by NareshDealer** [comment]
@rabay108  Yes i have installed it with v2.0 cloudformation stack and also had the role created automatically.

**Comment by rdifalco** [comment]
@NareshDealer this is because of a mishandled read-timeout by the AWS SDK. This error should be retried on or you can try increasing your read-timeout setting.
